#!/usr/bin/env php
<?php

require_once './vendor/autoload.php';

// call CLI
$app = require_once __DIR__ . '/bootstrap/app.php';

$out = $app->make(\Omega\Console\ConsoleKernel::class);

$handle = $out->handle($argv);

exit($handle);

